name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Eliminar contenedor anterior
        shell: powershell
        run: |
          $container = docker ps -a --filter "name=^html-app$" --format "{{.Names}}"

          if ($container -eq "html-app") {
            Write-Host "Contenedor html-app encontrado. Eliminándolo..."
            docker rm -f html-app
          }
          else {
            Write-Host "No existe un contenedor html-app anterior. Continuando..."
          }

      - name: Construir aplicación
        shell: powershell
        run: |
          docker build -t html-app:latest .

      - name: Ejecutar aplicación
        shell: powershell
        run: |
          docker run -d --name html-app --restart unless-stopped -p 8080:80 html-app:latest
