name: Deploy HTML

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Detener contenedor anterior
        shell: powershell
        run: |
          docker rm -f html-app 2>$null
          if ($LASTEXITCODE -ne 0) {
            Write-Host "No existe un contenedor html-app anterior. Continuando..."
          }
          exit 0

      - name: Construir aplicación
        shell: powershell
        run: |
          docker build -t html-app:latest .

      - name: Ejecutar aplicación
        shell: powershell
        run: |
          docker run -d --name html-app --restart unless-stopped -p 8080:80 html-app:latest
